// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __SimpleService_hh__
#define __SimpleService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE ysuga

_CORBA_MODULE_BEG

#ifndef __ysuga_mSimpleService__
#define __ysuga_mSimpleService__

  class SimpleService;
  class _objref_SimpleService;
  class _impl_SimpleService;
  
  typedef _objref_SimpleService* SimpleService_ptr;
  typedef SimpleService_ptr SimpleServiceRef;

  class SimpleService_Helper {
  public:
    typedef SimpleService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_SimpleService, SimpleService_Helper> SimpleService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_SimpleService,SimpleService_Helper > SimpleService_out;

#endif

  // interface SimpleService
  class SimpleService {
  public:
    // Declarations for this interface type.
    typedef SimpleService_ptr _ptr_type;
    typedef SimpleService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_SimpleService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Long read(::CORBA::Long& data);
    ::CORBA::Long write(::CORBA::Long data);
    ::CORBA::Long reset();

    inline _objref_SimpleService()  { _PR_setobj(0); }  // nil
    _objref_SimpleService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_SimpleService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_SimpleService(const _objref_SimpleService&);
    _objref_SimpleService& operator = (const _objref_SimpleService&);
    // not implemented

    friend class SimpleService;
  };

  class _pof_SimpleService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_SimpleService() : _OMNI_NS(proxyObjectFactory)(SimpleService::_PD_repoId) {}
    virtual ~_pof_SimpleService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_SimpleService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_SimpleService();

    virtual ::CORBA::Long read(::CORBA::Long& data) = 0;
    virtual ::CORBA::Long write(::CORBA::Long data) = 0;
    virtual ::CORBA::Long reset() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_SimpleService;

_CORBA_MODULE_END



_CORBA_MODULE POA_ysuga
_CORBA_MODULE_BEG

  class SimpleService :
    public virtual ysuga::_impl_SimpleService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~SimpleService();

    inline ::ysuga::SimpleService_ptr _this() {
      return (::ysuga::SimpleService_ptr) _do_this(::ysuga::SimpleService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_ysuga
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, ysuga::SimpleService_ptr _s);
void operator<<=(::CORBA::Any& _a, ysuga::SimpleService_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, ysuga::SimpleService_ptr& _s);



inline void
ysuga::SimpleService::_marshalObjRef(::ysuga::SimpleService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_SimpleService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_SimpleService
#endif

#endif  // __SimpleService_hh__

